[package]
name = "tray"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
tray-icon = "0.20.1"
windows = { version = "0.56", features = ["Win32_UI_WindowsAndMessaging"] }