name: Build binary
on:
    workflow_dispatch:
    push:
        branches:
            - rust
jobs:
    build-binary:
        name: Build binary
        runs-on: ubuntu-24.04-arm
        steps:
            - uses: actions/checkout@v6

            - run: sudo apt install -y libwebkit2gtk-4.1-dev

            # Setup
            - uses: oven-sh/setup-bun@v2
            - run: bun install

            - name: Build binary
              run: cargo build --verbose

            - run: cp target/debug/muziekdoosje-api ./muziekdoosje-api-arm64

            - uses: actions/upload-artifact@v7
              with:
                  name: muziekdoosje-api-arm64
                  path: ./muziekdoosje-api-arm64
                  archive: false
