name: Build binary
on:
    workflow_dispatch:
    push:
        branches:
            - rust
jobs:
    build-binary:
        name: Build binary (${{ matrix.target }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: linux-x64
                      binary: corelauncher-app
                      output: corelauncher-app-linux-x64
                    - os: windows-latest
                      target: windows-x64
                      binary: corelauncher-app.exe
                      output: corelauncher-app-windows-x64.exe
        steps:
            - uses: actions/checkout@v6

            - name: Install system dependencies (Linux)
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev

            - uses: oven-sh/setup-bun@v2
            - run: bun install

            - name: Build binary
              run: cargo build --verbose --release

            - name: Copy binary
              shell: bash
              run: cp target/release/${{ matrix.binary }} ./${{ matrix.output }}

            - uses: actions/upload-artifact@v7
              with:
                  name: ${{ matrix.target }}
                  path: ./${{ matrix.output }}
                  archive: false
