name: Generate release

permissions:
    contents: write

on:
    push:
        tags:
            - "v*"
        branches:
            - dev
jobs:
    release:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Update Version
              run: bun run update-version ${{ github.ref_name }}

            - name: Generate binaries
              run: bun run release

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./.dist/*
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
